LESSONS = [
    {
        "id": "py-01",
        "title": "Python: Hello World",
        "description": "Start your Python journey. Python's clean syntax makes it one of the most readable languages to learn.",
        "doc": "hello world print output display text basics beginner first program console printing print function start introduction",
    },
    {
        "id": "py-02",
        "title": "Python: Variables & Types",
        "description": "Python variables need no declaration keyword — just assign a value. Python figures out the type automatically.",
        "doc": "variables variable types type string strings integer integers float floats boolean booleans f-string fstring assign assignment value values data declare number numbers text conversion convert",
    },
    {
        "id": "py-03",
        "title": "Python: Lists & Loops",
        "description": "Python lists are ordered, changeable collections. The for loop in Python is cleaner and more direct than in most languages.",
        "doc": "list lists array arrays for loop loops looping iterate iteration iterating repeat repeating append index collection collections ordered enumerate range items elements",
    },
    {
        "id": "py-04",
        "title": "Python: Functions",
        "description": "Python functions use the def keyword. They support default parameters and can return multiple values.",
        "doc": "function functions def return parameter parameters argument arguments default value call invoke reuse code block define definition",
    },
    {
        "id": "py-05",
        "title": "Python: Dictionaries",
        "description": "Dictionaries store key-value pairs — the Python equivalent of JavaScript objects, and incredibly powerful.",
        "doc": "dictionary dictionaries dict key value pairs key-value hash map object objects lookup store data get items looping",
    },
    {
        "id": "py-06",
        "title": "Python: String Methods",
        "description": "Python strings have dozens of built-in methods for cleaning, searching, and transforming text.",
        "doc": "string strings methods upper lowercase strip replace split join text manipulation find search clean whitespace format transform title",
    },
    {
        "id": "py-07",
        "title": "Python: List Comprehensions",
        "description": "List comprehensions are a Pythonic shorthand for creating lists — concise, readable, and faster than a for loop.",
        "doc": "list comprehension comprehensions compact lists filter transform range expression pythonic shorthand create one line condition filtering transforming",
    },
    {
        "id": "py-08",
        "title": "Python: Classes & OOP",
        "description": "Classes are blueprints for creating objects. Object-Oriented Programming (OOP) organises code around data and behaviour.",
        "doc": "class classes object objects OOP object-oriented programming inheritance inherit init self method methods attribute attributes blueprint instance constructor define",
    },
    {
        "id": "py-09",
        "title": "Python: Error Handling",
        "description": "Real programs encounter unexpected input. try/except lets your code handle errors gracefully instead of crashing.",
        "doc": "error errors handling handle try except exception exceptions raise finally crash ValueError TypeError ZeroDivisionError catching catch gracefully bugs",
    },
    {
        "id": "py-10",
        "title": "Python: Standard Library",
        "description": "Python's standard library gives you hundreds of useful modules for maths, dates, random numbers, and more.",
        "doc": "import imports library libraries module modules math random datetime os standard sqrt pi random numbers dates times built-in",
    },
    {
        "id": "py-11",
        "title": "Python: Tuples & Sets",
        "description": "Tuples are immutable sequences. Sets are unordered collections of unique elements with fast membership testing.",
        "doc": "tuple tuples set sets immutable unique elements union intersection difference unordered collections operations packing unpacking",
    },
    {
        "id": "py-12",
        "title": "Python: *args & **kwargs",
        "description": "*args and **kwargs let functions accept any number of arguments — making them flexible without overloading.",
        "doc": "args kwargs variable arguments flexible function functions positional keyword unpack splat arbitrary any number",
    },
    {
        "id": "py-13",
        "title": "Python: Lambda & Higher-Order Functions",
        "description": "Lambda creates a one-liner anonymous function. map(), filter(), and sorted() accept functions as arguments.",
        "doc": "lambda anonymous function functions map filter sorted higher order callback one-liner functional programming transform select anonymous",
    },
    {
        "id": "py-14",
        "title": "Python: Generators",
        "description": "Generators produce values one at a time using yield — letting you work with infinite or very large sequences.",
        "doc": "generator generators yield lazy evaluation memory efficient infinite sequence sequences next iterator pause resume fibonacci large data",
    },
    {
        "id": "py-15",
        "title": "Python: Decorators",
        "description": "Decorators wrap a function to add behaviour before or after it runs — without changing the function itself.",
        "doc": "decorator decorators syntax wrap wrapping function modify behaviour logging timing caching metaprogramming functools wraps pattern",
    },
    {
        "id": "py-16",
        "title": "Python: Regular Expressions",
        "description": "Regular expressions (regex) are a mini-language for pattern matching inside strings.",
        "doc": "regex regular expressions expression pattern patterns match matching search findall sub replace email phone validation text extraction re module",
    },
    {
        "id": "py-17",
        "title": "Python: Type Hints & Dataclasses",
        "description": "Type hints document what types your functions expect and return. Dataclasses auto-generate boilerplate.",
        "doc": "type hints hint typing annotation annotations dataclass dataclasses auto-generate boilerplate field static analysis linting documentation data container",
    },
]
